"use client";

import { useState } from "react";
import {
  BookOpen,
  Sparkles,
  FileText,
  Upload,
  MessageCircle,
  Search,
  Users,
  Shield,
  ChevronRight,
  Play,
  Download,
  Settings,
  HelpCircle,
  Star,
  CheckCircle,
  ArrowRight,
  Zap,
  Target,
  Clock,
} from "lucide-react";
import { Button } from "@/components/ui/button";
import {
  Card,
  CardContent,
  CardDescription,
  CardHeader,
  CardTitle,
} from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import {
  Accordion,
  AccordionContent,
  AccordionItem,
  AccordionTrigger,
} from "@/components/ui/accordion";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import Link from "next/link";

export default function HelpPage() {
  const quickStartSteps = [
    {
      icon: Sparkles,
      title: "Generate Your First Document",
      description: "Use AI to create contracts, legal memos, and more",
      href: "/generate",
      time: "2 minutes",
    },
    {
      icon: Upload,
      title: "Upload & Enhance Documents",
      description: "Improve existing documents with AI assistance",
      href: "/enhance",
      time: "1 minute",
    },
    {
      icon: FileText,
      title: "Analyze Legal Documents",
      description: "Get insights and risk assessments",
      href: "/evaluate",
      time: "3 minutes",
    },
    {
      icon: MessageCircle,
      title: "Chat with AI Legal Assistant",
      description: "Get instant answers to legal questions",
      href: "/chat",
      time: "30 seconds",
    },
  ];

  const features = [
    {
      category: "Document Generation",
      icon: Sparkles,
      items: [
        {
          title: "Smart Drafting",
          description: "AI-powered document creation with legal templates",
          features: ["Contract templates", "Legal memos", "Instant generation"],
        },
        {
          title: "Template Library",
          description: "Access hundreds of legal document templates",
          features: [
            "State-specific forms",
            "Industry templates",
            "Custom templates",
          ],
        },
      ],
    },
    {
      category: "Document Analysis",
      icon: FileText,
      items: [
        {
          title: "Risk Assessment",
          description: "Identify potential legal risks in documents",
          features: ["Compliance checking", "Risk scoring", "Recommendations"],
        },
        {
          title: "Key Term Extraction",
          description: "Automatically extract important terms and clauses",
          features: [
            "Term highlighting",
            "Clause analysis",
            "Summary generation",
          ],
        },
      ],
    },
    {
      category: "Collaboration",
      icon: Users,
      items: [
        {
          title: "Team Management",
          description: "Collaborate with team members on documents",
          features: [
            "Role-based access",
            "Document sharing",
            "Team invitations",
          ],
        },
        {
          title: "Real-time Editing",
          description: "Edit documents together in real-time",
          features: ["Live collaboration", "Version control", "Comment system"],
        },
      ],
    },
  ];

  const faqs = [
    {
      question: "How does AI document generation work?",
      answer:
        "Our AI analyzes your requirements and generates legal documents using advanced language models trained on legal text. You provide the basic information, and our AI creates a comprehensive document following legal standards and best practices.",
    },
    {
      question: "Are the generated documents legally binding?",
      answer:
        "The documents generated by our AI are professionally formatted and include standard legal language. However, we recommend having any important legal documents reviewed by a qualified attorney before use, as legal requirements can vary by jurisdiction.",
    },
    {
      question: "How secure is my data?",
      answer:
        "We use enterprise-grade security with end-to-end encryption. Your documents are stored securely and are only accessible to you and team members you explicitly grant access to. We comply with industry standards for data protection.",
    },
    {
      question: "Can I customize the generated documents?",
      answer:
        "Yes! All generated documents can be edited and customized using our built-in editor. You can modify text, add clauses, change formatting, and save different versions of your documents.",
    },
    {
      question: "What file formats are supported?",
      answer:
        "We support common document formats including PDF, DOCX, and plain text. You can upload documents in these formats for analysis and download your generated documents in your preferred format.",
    },
    {
      question: "How does team collaboration work?",
      answer:
        "You can create teams, invite members with different roles (viewer, editor, admin), and share documents. Team members can collaborate in real-time, leave comments, and track changes together.",
    },
    {
      question: "Is there a limit to document generation?",
      answer:
        "Usage limits depend on your subscription plan. Free accounts have basic limits, while premium plans offer increased limits and additional features. Check your account settings for current usage.",
    },
    {
      question: "Can I integrate with other tools?",
      answer:
        "We're working on integrations with popular legal and business tools. Currently, you can download documents in standard formats for use with other applications.",
    },
  ];

  return (
    <div className="container mx-auto px-4 py-8 space-y-8">
      {/* Header */}
      <div className="text-center space-y-4">
        <div className="w-16 h-16 bg-gradient-to-br from-primary to-primary/80 rounded-2xl flex items-center justify-center mx-auto">
          <BookOpen className="h-8 w-8 text-primary-foreground" />
        </div>
        <h1 className="text-3xl lg:text-4xl font-bold">Help & Guide</h1>
        <p className="text-lg text-muted-foreground max-w-2xl mx-auto">
          Everything you need to know to get the most out of Lawverra's
          AI-powered legal tools
        </p>
      </div>

      {/* Quick Start */}
      <Card className="border-primary/20 bg-gradient-to-br from-primary/5 to-background">
        <CardHeader className="text-center">
          <CardTitle className="flex items-center justify-center gap-2 text-2xl">
            <Zap className="h-6 w-6 text-primary" />
            Quick Start Guide
          </CardTitle>
          <CardDescription>
            Get started with these essential features in under 10 minutes
          </CardDescription>
        </CardHeader>
        <CardContent>
          <div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4">
            {quickStartSteps.map((step, index) => (
              <Link key={index} href={step.href} className="group">
                <Card className="h-full border-2 hover:border-primary/50 transition-all duration-300 hover:shadow-lg cursor-pointer">
                  <CardHeader className="pb-4">
                    <div className="flex items-center justify-between">
                      <div className="w-10 h-10 bg-gradient-to-br from-primary to-primary/80 rounded-lg flex items-center justify-center">
                        <step.icon className="h-5 w-5 text-primary-foreground" />
                      </div>
                      <Badge variant="secondary" className="text-xs">
                        <Clock className="h-3 w-3 mr-1" />
                        {step.time}
                      </Badge>
                    </div>
                    <CardTitle className="text-base group-hover:text-primary transition-colors">
                      {step.title}
                    </CardTitle>
                  </CardHeader>
                  <CardContent>
                    <p className="text-sm text-muted-foreground mb-3">
                      {step.description}
                    </p>
                    <div className="flex items-center text-sm text-primary group-hover:translate-x-1 transition-transform">
                      Get Started <ArrowRight className="h-4 w-4 ml-1" />
                    </div>
                  </CardContent>
                </Card>
              </Link>
            ))}
          </div>
        </CardContent>
      </Card>

      {/* Main Content */}
      <Tabs defaultValue="features" className="space-y-6">
        <TabsList className="grid w-full max-w-md grid-cols-3 mx-auto">
          <TabsTrigger value="features">Features</TabsTrigger>
          <TabsTrigger value="tutorials">Tutorials</TabsTrigger>
          <TabsTrigger value="faq">FAQ</TabsTrigger>
        </TabsList>

        <TabsContent value="features" className="space-y-6">
          <div className="space-y-8">
            {features.map((category, index) => (
              <Card key={index}>
                <CardHeader>
                  <CardTitle className="flex items-center gap-2">
                    <category.icon className="h-5 w-5 text-primary" />
                    {category.category}
                  </CardTitle>
                </CardHeader>
                <CardContent>
                  <div className="grid gap-6 sm:grid-cols-2">
                    {category.items.map((item, itemIndex) => (
                      <div key={itemIndex} className="space-y-3">
                        <div>
                          <h4 className="font-semibold mb-1">{item.title}</h4>
                          <p className="text-sm text-muted-foreground">
                            {item.description}
                          </p>
                        </div>
                        <ul className="space-y-1">
                          {item.features.map((feature, featureIndex) => (
                            <li
                              key={featureIndex}
                              className="flex items-center text-sm"
                            >
                              <CheckCircle className="h-4 w-4 text-green-500 mr-2 flex-shrink-0" />
                              {feature}
                            </li>
                          ))}
                        </ul>
                      </div>
                    ))}
                  </div>
                </CardContent>
              </Card>
            ))}
          </div>
        </TabsContent>

        <TabsContent value="tutorials" className="space-y-6">
          <div className="grid gap-6 sm:grid-cols-2 lg:grid-cols-3">
            <Card className="group hover:shadow-lg transition-all duration-300">
              <CardHeader>
                <div className="w-12 h-12 bg-gradient-to-br from-blue-500 to-blue-600 rounded-lg flex items-center justify-center mb-3">
                  <Play className="h-6 w-6 text-white" />
                </div>
                <CardTitle className="text-lg">
                  Creating Your First Contract
                </CardTitle>
                <CardDescription>
                  Step-by-step guide to generate a professional contract
                </CardDescription>
              </CardHeader>
              <CardContent>
                <div className="space-y-2 text-sm">
                  <div className="flex items-center gap-2">
                    <Badge variant="outline">5 min</Badge>
                    <Badge variant="outline">Beginner</Badge>
                  </div>
                  <p className="text-muted-foreground">
                    Learn how to use our AI to create professional contracts
                    with proper legal language and formatting.
                  </p>
                </div>
              </CardContent>
            </Card>

            <Card className="group hover:shadow-lg transition-all duration-300">
              <CardHeader>
                <div className="w-12 h-12 bg-gradient-to-br from-green-500 to-green-600 rounded-lg flex items-center justify-center mb-3">
                  <Search className="h-6 w-6 text-white" />
                </div>
                <CardTitle className="text-lg">
                  Document Analysis Deep Dive
                </CardTitle>
                <CardDescription>
                  Master document review and risk assessment features
                </CardDescription>
              </CardHeader>
              <CardContent>
                <div className="space-y-2 text-sm">
                  <div className="flex items-center gap-2">
                    <Badge variant="outline">8 min</Badge>
                    <Badge variant="outline">Intermediate</Badge>
                  </div>
                  <p className="text-muted-foreground">
                    Understand how to analyze documents for risks, extract key
                    terms, and get actionable insights.
                  </p>
                </div>
              </CardContent>
            </Card>

            <Card className="group hover:shadow-lg transition-all duration-300">
              <CardHeader>
                <div className="w-12 h-12 bg-gradient-to-br from-purple-500 to-purple-600 rounded-lg flex items-center justify-center mb-3">
                  <Users className="h-6 w-6 text-white" />
                </div>
                <CardTitle className="text-lg">
                  Team Collaboration Setup
                </CardTitle>
                <CardDescription>
                  Set up teams and collaborate on documents effectively
                </CardDescription>
              </CardHeader>
              <CardContent>
                <div className="space-y-2 text-sm">
                  <div className="flex items-center gap-2">
                    <Badge variant="outline">6 min</Badge>
                    <Badge variant="outline">Beginner</Badge>
                  </div>
                  <p className="text-muted-foreground">
                    Learn to create teams, invite members, and manage
                    collaborative document workflows.
                  </p>
                </div>
              </CardContent>
            </Card>
          </div>

          <Card className="bg-gradient-to-r from-primary/10 to-primary/5">
            <CardHeader className="text-center">
              <CardTitle>Video Tutorials Coming Soon!</CardTitle>
              <CardDescription>
                We're creating comprehensive video tutorials to help you master
                every feature
              </CardDescription>
            </CardHeader>
            <CardContent className="text-center">
              <Button variant="outline" disabled>
                <Star className="h-4 w-4 mr-2" />
                Get Notified
              </Button>
            </CardContent>
          </Card>
        </TabsContent>

        <TabsContent value="faq" className="space-y-6">
          <Card>
            <CardHeader>
              <CardTitle className="flex items-center gap-2">
                <HelpCircle className="h-5 w-5 text-primary" />
                Frequently Asked Questions
              </CardTitle>
              <CardDescription>
                Find answers to common questions about Lawverra's features and
                functionality
              </CardDescription>
            </CardHeader>
            <CardContent>
              <Accordion type="single" collapsible className="space-y-2">
                {faqs.map((faq, index) => (
                  <AccordionItem
                    key={index}
                    value={`item-${index}`}
                    className="border rounded-lg px-4"
                  >
                    <AccordionTrigger className="text-left hover:no-underline">
                      {faq.question}
                    </AccordionTrigger>
                    <AccordionContent className="text-muted-foreground">
                      {faq.answer}
                    </AccordionContent>
                  </AccordionItem>
                ))}
              </Accordion>
            </CardContent>
          </Card>
        </TabsContent>
      </Tabs>

      {/* Contact Support */}
      <Card className="bg-gradient-to-r from-primary to-primary/80 text-white">
        <CardHeader className="text-center">
          <CardTitle className="text-2xl">Still Need Help?</CardTitle>
          <CardDescription className="text-white/90">
            Our support team is here to assist you with any questions
          </CardDescription>
        </CardHeader>
        <CardContent className="text-center space-y-4">
          <div className="flex flex-col sm:flex-row items-center justify-center gap-4">
            <Button variant="secondary" size="lg" asChild>
              <Link href="/support">
                <MessageCircle className="h-4 w-4 mr-2" />
                Contact Support
              </Link>
            </Button>
            <Button
              variant="outline"
              size="lg"
              className="border-white/20 text-white hover:bg-white/10"
            >
              <Download className="h-4 w-4 mr-2" />
              Download Guide
            </Button>
          </div>
        </CardContent>
      </Card>
    </div>
  );
}
