import { Metadata } from "next";
import { Card, CardContent } from "@/components/ui/card";

export const metadata: Metadata = {
  title: "Terms of Use",
  description: "Lawverra's terms of use and service agreement",
};

export default function TermsPage() {
  return (
    <div className="min-h-screen bg-background">
      <div className="container mx-auto px-6 py-16">
        <div className="max-w-4xl mx-auto">
          <h1 className="text-4xl font-bold mb-8 text-foreground">
            Terms of Use
          </h1>

          <Card className="bg-card">
            <CardContent className="pt-6">
              <div className="prose prose-lg max-w-none prose-headings:text-foreground prose-p:text-muted-foreground prose-strong:text-foreground">
                <p>
                  <strong>Effective Date: June 13, 2025</strong>
                </p>

                <p>
                  Welcome to Lawverra. These Terms of Use ("Terms") govern your
                  access to and use of our website, platform, and related
                  services (collectively, the "Services"). By using Lawverra,
                  you agree to these Terms. If you do not agree, you may not use
                  the Services.
                </p>

                <h2>1. Eligibility and Access</h2>
                <ul className="list-disc pl-6 space-y-2">
                  <li>
                    Lawverra is intended for licensed legal professionals, legal
                    operations teams, and qualified business users managing
                    contracts and legal documentation.
                  </li>
                  <li>
                    You must be at least 18 years old to create an account.
                  </li>
                </ul>

                <h2>2. Service Scope and Limitations</h2>
                <ul className="list-disc pl-6 space-y-2">
                  <li>
                    Lawverra provides AI-powered document drafting, review, and
                    analysis tools. These are designed to augment—not
                    replace—professional legal review.
                  </li>
                  <li>
                    No content generated by Lawverra constitutes legal advice.
                  </li>
                </ul>

                <h2>3. Your Responsibilities</h2>
                <ul className="list-disc pl-6 space-y-2">
                  <li>
                    You are solely responsible for ensuring that all documents
                    used or generated via Lawverra comply with applicable laws
                    and professional standards.
                  </li>
                  <li>
                    You agree to maintain the confidentiality of your login
                    credentials and report any suspected security breaches.
                  </li>
                </ul>

                <h2>4. Intellectual Property</h2>
                <ul className="list-disc pl-6 space-y-2">
                  <li>
                    All content, design, software, trademarks, and intellectual
                    property on or associated with Lawverra remain the exclusive
                    property of the company.
                  </li>
                  <li>
                    You may not reproduce, copy, or distribute any part of the
                    Services without prior written permission.
                  </li>
                </ul>

                <h2>5. Termination</h2>
                <ul className="list-disc pl-6 space-y-2">
                  <li>
                    We may suspend or terminate your access if you violate these
                    Terms or misuse the Services in any way.
                  </li>
                </ul>

                <h2>6. Modifications to the Terms</h2>
                <ul className="list-disc pl-6 space-y-2">
                  <li>
                    We reserve the right to modify these Terms at any time. We
                    will provide notice of changes, and continued use of the
                    Services signifies your acceptance.
                  </li>
                </ul>
              </div>
            </CardContent>
          </Card>
        </div>
      </div>
    </div>
  );
}
